# SysWatch Threshold Configuration

# CPU usage alert threshold
CPU_THRESHOLD=80

# Memory usage alert threshold
MEMORY_THRESHOLD=75

# Disk usage alert threshold
DISK_THRESHOLD=85

PING_TARGET=google.com
